#cloud-config
ssh-pwauth: no
users:
- name: yc-user
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh-authorized-keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDnUHhUfPX9xRkuVJmyp0wgBtgU82ZzPxSpQ62V82KmzU0oNI8maepGkIoppEOXQmNriX5mH5jg0PONKbYAQMFENFEByM11iyBHzgssDsUne05/JD2pufewPgY3mtZW5Rq6kXpDXlKTuYEw6f7gYxHU9NjluwSJc+EJoaD6sbnDwC7U1wvew9SGwC9rEVOMjURi7STtd8lb1d2cTQ/L2MnEb4uKuSO5wS0F/gaE31ulLQ2QAqirZytzXYYGsEUdW9/a2GfEMsJRbjs8qlQQUYz69PoUtuBWUvofc5FOftl7GLrJ48JWe30vUX0PspJdb1AF0mGeuQ2ZCgi2WAnTZ1m105NFtDhpznw3AvKvbQiW/uTqPZMmmUgSg2Iwunh54jed1wXr3LLOEhBsaR0n01gpD6RePPI39AUw9RizDa+DGIB0GvKIIouFa/hkXENVQuRwJ9sYhNnEvl1/F1t5LmPkv7ctYa298usGOwaKVmiCKOT3LFfRWb5QpDg6bZWuFZs= appuser
runcmd:
- 'wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -'
- 'echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list'
- 'apt-get update && apt-get upgrade -y'
- 'apt-get install -y ruby-full ruby-bundler build-essential mongodb-org git'
- 'systemctl enable mongod && systemctl start mongod'
- 'cd /home/yc-user && git clone -b monolith https://github.com/express42/reddit.git'
- 'cd ./reddit && bundle install && puma -d'
